### ISSUE TITLE
A discotech in June

### ISSUE THREAD

**Issue by bnchdrff** [detroit-js-peer-edu/detroit-js-peer-edu.github.io#4]
I have been corresponding with Tawana, the manager of discotechs. I told her that I'm a part of a group of programmers interested in teaching.

> The next Data DiscoTech is going to be at the Boggs School. Because of programming and capacity, they need to have it during the week, June 2nd from 430pm to 7pm. Are you available during that time? Also, we're trying to cater many of the stations around the young people. Would it be possible to program a station that young people could learn from also?

Anyone interested in setting up a learning station?

Read about discotechs here: https://www.alliedmedia.org/ddjc/discotech

**Comment by bnchdrff** [comment]
@john-g-g @mlangens @mariewalker @ao5357 @jessicamcinchak any interest / availability?

**Comment by bnchdrff** [comment]
also @hillarycp of course

**Comment by jessicamcinchak** [comment]
i'm in!

**Comment by mlangens** [comment]
I'm in, also!

**Comment by mariewalker** [comment]
Hmm.. I was going to say that I am in, but I have already two things going on that night that I have to decide on (work or soccer). I might be able to swing though the first hour.. will have to check back on that later. Great to hear about the opportunity!

**Comment by jessicamcinchak** [comment]
Let's coordinate soon if we're interested in hosting a station together! Tawana sent a note today asking for final station teams/ideas by 3/20.
